### ISSUE TITLE
the usage of datasets

### ISSUE THREAD

**Issue by xxxxxy211** [akhila-s-rao/mobile-network-datasets-ns3#1]
hi，akihila：
  I download this project and I found thers is some error in the data-processing-scripts.Is the error in ipynb files is important for the data processing?

thanks for your reply!
Xinyu Chen.

**Comment by xxxxxy211** [comment]
in adition, could you tell me how to use this datasets?

**Comment by akhila-s-rao** [comment]
Hi !
Could you please share the error you see ? 
The data-processing script processes raw ns3 logs into a tabular format that is easy to feed into machine learning algorithms.

This dataset contains base station side and UE side logs from a deployment with multiple macro and micro cells. 
It has been created to learn models for predicting various performance metrics from either the UE or the base station side.
Please look at the different log files available and the column names to get an idea of what observations/metrics are available.

**Comment by xxxxxy211** [comment]
Your reply is very helpful to me, I think I misunderstood the meaning of this warehouse (my research is related to Internet of Vehicles, there are some differences with your simulation experiments). Of course, my idea is also to use machine learning methods to analyze communication performance.
Anyway, thank you very much for your reply!
Xinyu Chen.
